export interface FuelComponent {
  id: string;
  name: string;
  shortCode: string;
  zone: "Rear Chassis (Underbody)" | "Chassis Rail (Passenger Side)" | "Engine Bay (Passenger Side)" | "Engine Block (Intake Side)";
  photoUrl: string;
  photoTitle: string;
  function: string;
  pressureState: "Negative Pressure (Suction / Vacuum)" | "Low Pressure Feed (6 - 8 bar)" | "Extreme High Pressure (145 - 155 kg/cm²)" | "Atmospheric Spill Return";
  keySpecs: string;
  failureSymptoms: string[];
  disassemblyGuide: string[];
  serviceInterval: string;
}

export interface FuelServiceGuide {
  id: string;
  title: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  estimatedTime: string;
  toolsNeeded: string[];
  consumables: string[];
  overview: string;
  steps: {
    stepNumber: number;
    title: string;
    instruction: string;
    warning?: string;
    torque?: string;
  }[];
}

export const FUEL_CIRCUIT_COMPONENTS: FuelComponent[] = [
  {
    id: "fuel-tank-pickup",
    name: "Fuel Tank, Sender Unit & Brass Mesh Sock Strainer",
    shortCode: "TANK-SOCK",
    zone: "Rear Chassis (Underbody)",
    photoUrl: "./reference/fuel_tank_pickup.jpg",
    photoTitle: "Fuel Tank Sender Flange & Brass Mesh Sock Strainer",
    function: "Stores 65 liters of diesel. The suction pipe pulls fuel from the bottom sump of the tank through a fine brass mesh sock strainer. Note: No electric fuel pump exists in this tank; the system relies 100% on suction generated by the VE pump on the engine.",
    pressureState: "Negative Pressure (Suction / Vacuum)",
    keySpecs: "Capacity: 65 Liters (17.2 US gal) | Pickup Tube OD: 8.0 mm (5/16\") | Return Tube OD: 6.0 mm (1/4\")",
    failureSymptoms: [
      "Engine runs fine at idle and low speeds, but cuts out / coughs violently above 2,800 RPM under load",
      "Strainer blocked by black diesel bug (Cladosporium resinae algae) or rust flakes",
      "Fuel tank breather check valve stuck, creating extreme vacuum inside tank (whooshing sound when opening filler cap)"
    ],
    disassemblyGuide: [
      "1. Support rear axle on jackstands and disconnect negative battery terminal.",
      "2. Drain remaining diesel by removing the 14mm hex drain plug on the bottom rear of the steel tank.",
      "3. Disconnect the 8mm rubber suction hose, 6mm return hose, and breather line from the sender flange.",
      "4. Unplug the 3-pin round fuel level sender wiring harness.",
      "5. Support tank with transmission jack and remove the 4x 14mm tank strap bolts.",
      "6. Lower tank, unbolt 5x Phillips screws securing the round sender flange, and extract the pickup assembly with float arm.",
      "7. Inspect brass sock strainer; wash in clean diesel solvent and blow out with compressed air from inside out."
    ],
    serviceInterval: "Inspect & clean every 100,000 km (or after contaminated fuel fill-up)"
  },
  {
    id: "fuel-filter-primer",
    name: "Fuel Filter Assembly, Manual Primer Pump & Water Sedimenter",
    shortCode: "FILTER-SED",
    zone: "Engine Bay (Passenger Side)",
    photoUrl: "./reference/fuel_filter_primer.jpg",
    photoTitle: "Fuel Filter Primer Bracket & Water Sedimenter Bowl",
    function: "Filters particles down to 5 microns, separates suspended water droplets, and houses the manual push-button primer diaphragm to purge air from the suction line.",
    pressureState: "Negative Pressure (Suction / Vacuum)",
    keySpecs: "Filter Element: Toyota 23303-64010 / 23303-54011 | Sedimenter Switch: 2-pin float (84461-60040) | Drain Cock: 10mm Wing Nut",
    failureSymptoms: [
      "Primer pump button stays soft and spongy, never becoming hard to push (torn internal rubber diaphragm or stuck check valve)",
      "Air is sucked past the filter upper O-ring, causing long cranking times after vehicle sits overnight",
      "Amber 'Fuel Pump with Droplets' warning icon illuminates on instrument cluster (water level in bottom bowl is high)"
    ],
    disassemblyGuide: [
      "1. Place a catch pan beneath fuel filter assembly on passenger inner fender.",
      "2. Loosen bottom plastic wing-nut drain cock and 10mm air vent screw on top to drain fuel from filter.",
      "3. Unplug 2-pin electrical connector for the water level sensor float switch.",
      "4. Using a strap wrench or filter pliers, spin off the entire filter cartridge from the aluminum primer head.",
      "5. Unscrew the lower clear plastic sedimenter bowl from the bottom of the old filter cartridge.",
      "6. Clean sedimenter bowl, install new Viton O-ring (lubricated with diesel), and screw bowl onto new filter hand-tight.",
      "7. Lubricate top rubber gasket with clean diesel and spin new filter onto primer head until gasket contacts base, then tighten 3/4 turn by hand.",
      "8. Close bottom drain cock, open top 10mm bleed screw, and pump manual primer button until pure diesel squirts out without air bubbles."
    ],
    serviceInterval: "Replace filter cartridge every 20,000 km | Drain sedimenter every 5,000 km"
  },
  {
    id: "ve-inlet-banjo-screen",
    name: "Bosch VE Pump Inlet Banjo Bolt & 10mm Micro-Mesh Screen",
    shortCode: "BANJO-SCREEN",
    zone: "Engine Block (Intake Side)",
    photoUrl: "./reference/ve_fuel_cut.jpg",
    photoTitle: "VE Pump Fuel Inlet Fitting & Internal Screen Location",
    function: "The last line of defense protecting the high-precision rotary vane pump and distributor plunger from micro-debris. Located inside the 17mm fuel inlet union banjo fitting on the injection pump body.",
    pressureState: "Negative Pressure (Suction / Vacuum)",
    keySpecs: "Screen Diameter: 10.0 mm | Mesh: Stainless Steel 80-Micron | Banjo Bolt Size: M12 x 1.25 (17mm Hex)",
    failureSymptoms: [
      "Engine stumbles under heavy turbo boost even with a brand new fuel filter installed",
      "Mysterious power loss after driving through high-RPM highway climbs",
      "Pump makes a high-pitched whining cavitation noise due to severe suction restriction"
    ],
    disassemblyGuide: [
      "1. Clean surrounding area around fuel inlet on the VE pump with brake cleaner.",
      "2. Using a 17mm box wrench, unbolt the fuel inlet union banjo bolt on the side of the pump.",
      "3. Discard the two copper crush washers (always use new ones on assembly).",
      "4. Look inside the threaded pump inlet hole: A tiny 10mm conical spring and stainless mesh screen sit recessed inside.",
      "5. Use a small dentist pick or bent wire to carefully extract the spring and micro-screen.",
      "6. Spray screen with carb cleaner in reverse direction to blast out trapped black algae sludge and lint.",
      "7. Reinstall screen, spring, banjo fitting with 2x new copper washers, and torque banjo bolt to 25 Nm (18 ft-lb)."
    ],
    serviceInterval: "Inspect & clean whenever diagnosing mysterious high-RPM power starvation"
  },
  {
    id: "ve-transfer-pump",
    name: "Bosch VE Rotary Vane Transfer Pump & Pressure Regulating Valve",
    shortCode: "VANE-PUMP",
    zone: "Engine Block (Intake Side)",
    photoUrl: "./reference/ve_fuel_cut.jpg",
    photoTitle: "Internal VE Pump Sliding Vane Suction & Transfer Assembly",
    function: "Located inside the front housing of the VE pump. As the drive shaft spins, 4 sliding spring-loaded steel vanes draw diesel from the fuel tank and pressurize the internal pump housing to 6–8 bar (85–115 psi). This internal pressure drives the hydraulic dynamic timing advance piston.",
    pressureState: "Low Pressure Feed (6 - 8 bar)",
    keySpecs: "Transfer Pressure at Idle (700 RPM): 2.5 – 3.5 bar | At 2,500 RPM: 6.5 – 8.0 bar | Regulating Valve: 10mm Hex Pin",
    failureSymptoms: [
      "Low internal transfer pressure fails to advance injection timing under RPM, causing sluggish acceleration, heavy gray smoke, and high EGTs",
      "Pressure regulating valve spool stuck open from dirty fuel, bypassing all suction vacuum back to inlet"
    ],
    disassemblyGuide: [
      "1. Internal transfer pump requires complete VE pump bench teardown by an authorized diesel specialist.",
      "2. On-engine diagnostic: Check internal housing pressure by installing a 0-15 bar pressure gauge into the top vent/out-bolt port.",
      "3. External adjustment: The 10mm hex regulating valve on the pump side can be tapped lightly with a brass punch to restore lost pressure."
    ],
    serviceInterval: "Service during injection pump overhaul (typically 250,000+ km)"
  },
  {
    id: "lda-boost-compensator",
    name: "Bosch VE Aneroid LDA Boost Compensator (Smoke & Boost Fueling)",
    shortCode: "LDA-COMP",
    zone: "Engine Block (Intake Side)",
    photoUrl: "./reference/ve_fuel_cut.jpg",
    photoTitle: "VE Pump Top Aluminum LDA Boost Compensator Capsule",
    function: "Modulates fuel delivery relative to turbocharger boost pressure. Manifold boost pressure acts on the top rubber diaphragm, pushing a contoured eccentric steel cone downward against a star-wheel spring, allowing the fuel metering lever to travel further for maximum torque under boost.",
    pressureState: "Low Pressure Feed (6 - 8 bar)",
    keySpecs: "Diaphragm OD: 65 mm | Boost Reference: 4mm Silicone Hose from Crossover | Spring Preload: Internal Star Wheel",
    failureSymptoms: [
      "Engine has zero boost enrichment, feels completely gutless like a naturally aspirated diesel (torn diaphragm or disconnected boost hose)",
      "Excessive black smoke cloud off idle before turbo spools (smoke set-screw turned too far down)"
    ],
    disassemblyGuide: [
      "1. Clean top of VE injection pump thoroughly.",
      "2. Remove 4x slotted screws securing the aluminum top cap.",
      "3. Scribe a reference alignment line across the rubber diaphragm and pump housing.",
      "4. Pull the rubber diaphragm and attached eccentric steel cone straight upward.",
      "5. Inspect rubber for pinhole splits or fuel oil saturating the top chamber.",
      "6. Rotate the eccentric cone to change fuel ramp slope: Steepest ramp facing front provides maximum aggressive fuel under boost.",
      "7. Adjust internal star-wheel tooth ring: Turn clockwise to soften spring (boost fuel starts earlier) or counter-clockwise for stiffer spring.",
      "8. Reinstall diaphragm, top cover, and tighten 4x screws to 8 Nm."
    ],
    serviceInterval: "Inspect diaphragm every 50,000 km or when tuning boost"
  },
  {
    id: "injector-spill-rail",
    name: "Fuel Injector High-Pressure Lines & Leak-Off Spill Rail",
    shortCode: "SPILL-RAIL",
    zone: "Engine Block (Intake Side)",
    photoUrl: "./reference/engine_bay.jpg",
    photoTitle: "4x High Pressure Lines & Aluminum Leak-Off Return Rail",
    function: "The 4x steel 17mm lines deliver 150 bar fuel pulses from the delivery valves to each injector. Any excess diesel used to lubricate injector needles drains through the aluminum spill rail and returns back to the fuel tank through a restricted return banjo bolt.",
    pressureState: "Extreme High Pressure (145 - 155 kg/cm²)",
    keySpecs: "Line Flare Nut: 17mm (29 Nm) | Spill Rail Banjo Nuts: 17mm (29 Nm) | Return Orifice Out-Bolt: Marked 'OUT' (0.5mm orifice)",
    failureSymptoms: [
      "Fuel misting or wet diesel pooling on cylinder head near injector wells (cracked steel line or failed aluminum crush washer)",
      "Engine runs rough / misfires due to aerated high-pressure lines",
      "Using standard banjo bolt instead of the factory 'OUT' restricted bolt on the VE return fitting causes lost internal pump pressure"
    ],
    disassemblyGuide: [
      "1. Use a 17mm flare nut line wrench to loosen high-pressure steel lines at both VE pump and injector holders.",
      "2. Remove plastic vibration dampening line clamps (never leave lines unclamped; engine vibration snaps steel lines!).",
      "3. Unbolt 4x 17mm banjo nuts securing aluminum leak-off return rail.",
      "4. Discard all 8x aluminum/copper crush washers. Always install brand new washers to prevent external diesel leaks onto hot exhaust manifold.",
      "5. Torque injector leak-off nuts to 29 Nm and steel line flare nuts to 29 Nm (21 ft-lb)."
    ],
    serviceInterval: "Replace all crush washers whenever injector lines are removed"
  }
];

export const FUEL_SERVICE_GUIDES: FuelServiceGuide[] = [
  {
    id: "air-ingress-debug",
    title: "Air Ingress (Cavitation) Diagnostic Protocol & Clear Line Test",
    difficulty: "Beginner",
    estimatedTime: "45 Minutes",
    toolsNeeded: ["1 Meter of 5/16\" (8mm) Clear Vinyl Hose", "2x Hose Clamps", "Flashlight", "Vacuum Gauge"],
    consumables: ["5/16\" Diesel-Rated Rubber Fuel Hose (Gates Barricade)", "Stainless Worm-Drive Clamps"],
    overview: "Because the 2L-T has no in-tank lift pump, the entire line from tank to injection pump operates under continuous suction vacuum. A microscopic pinhole leak or loose clamp will suck air into the diesel instead of leaking fuel out, causing long cranking times, rough surging idle, and lost power.",
    steps: [
      {
        stepNumber: 1,
        title: "Install Clear Vinyl Line at Injection Pump Inlet",
        instruction: "Disconnect the black rubber fuel supply hose from the VE injection pump fuel inlet. Install a 30 cm length of 5/16\" clear vinyl hose between the fuel filter outlet and the pump inlet using clamps.",
        warning: "Clear vinyl hose is for diagnostic testing only; replace with reinforced diesel fuel hose before road driving."
      },
      {
        stepNumber: 2,
        title: "Prime & Observe Fuel Flow",
        instruction: "Pump the manual fuel filter primer button until firm. Start the engine and shine a bright flashlight through the clear vinyl line while revving engine to 2,500 RPM.",
        warning: "Watch for continuous streams of tiny 'champagne bubbles' or large air pockets tumbling through the line."
      },
      {
        stepNumber: 3,
        title: "Isolate Air Ingress Source (Filter vs Chassis Line)",
        instruction: "If bubbles are present:\n• Move the clear vinyl hose to the INPUT of the fuel filter (between chassis hard line and filter inlet).\n• If bubbles disappear: The leak is inside the fuel filter primer head, water sensor O-ring, or filter cartridge seal.\n• If bubbles remain: The leak is along the chassis hard lines, tank pickup hose, or cracked sender pipe."
      },
      {
        stepNumber: 4,
        title: "Measure Suction Line Vacuum Resistance",
        instruction: "Connect a vacuum gauge into the suction line between filter and pump. At 2,500 RPM under load, suction vacuum must NOT exceed 150 mmHg (6 inHg). Vacuum > 200 mmHg indicates severe restriction (clogged tank sock or collapsed filter media).",
        warning: "High vacuum causes fuel cavitation (boiling diesel under negative pressure), forming air pockets."
      }
    ]
  },
  {
    id: "complete-fuel-bleeding",
    title: "Complete Fuel System Air Bleeding Sequence (Dry Tank / Filter to Injectors)",
    difficulty: "Beginner",
    estimatedTime: "20 Minutes",
    toolsNeeded: ["10mm Wrench", "17mm Flare Nut Line Wrench", "Shop Rags"],
    consumables: ["Clean Diesel Fuel", "New 10mm Bleed Screw Washer"],
    overview: "Follow this factory procedure after running out of fuel, replacing the fuel filter, or replacing the injection pump to start the engine on the first crank without burning out the starter motor.",
    steps: [
      {
        stepNumber: 1,
        title: "Bleed Fuel Filter Assembly",
        instruction: "Loosen the 10mm air vent bolt on top of the aluminum fuel filter primer head 2 full turns. Wrap a rag around the screw. Pump the top primer button repeatedly with steady downward strokes until pure bubble-free diesel squirts out. Tighten 10mm bolt to 6 Nm while still pumping.",
        torque: "Bleed Bolt: 6 Nm (53 in-lb)"
      },
      {
        stepNumber: 2,
        title: "Pressurize Bosch VE Injection Pump Body",
        instruction: "Continue pumping the primer button 20 to 30 more strokes after tightening the bleed bolt. The button will become noticeably rock-hard to press as the internal pump cavity fills with fuel."
      },
      {
        stepNumber: 3,
        title: "Crack Open 17mm Injector Flare Nuts",
        instruction: "Using a 17mm line wrench, loosen the steel fuel line nuts at Cylinders #1, #2, and #3 injectors by 1/2 turn. Wrap a shop towel over the injector tops to catch spray.",
        warning: "Wear safety glasses and gloves. Diesel injection pressure exceeds 2,000 psi."
      },
      {
        stepNumber: 4,
        title: "Crank Engine to Expel Air from High-Pressure Lines",
        instruction: "Have an assistant crank the engine for 5 to 8 seconds with the accelerator pedal held halfway down. Watch for foaming diesel and air bubbles escaping from the cracked flare nuts.",
        warning: "Do not crank starter for more than 10 seconds continuously; allow starter motor to cool 30 seconds between cranking bursts."
      },
      {
        stepNumber: 5,
        title: "Torque Flare Nuts & Start Engine",
        instruction: "As soon as solid liquid fuel spurts rhythmically from the nuts, stop cranking. Tighten all 3 17mm flare nuts to 29 Nm (21 ft-lb). Turn key: Engine will fire instantly and settle into a smooth idle.",
        torque: "Flare Nuts: 29 Nm (21 ft-lb)"
      }
    ]
  },
  {
    id: "bottle-feed-bypass",
    title: "Stranded Off-Road Gravity & Bottle-Feed Emergency Bypass",
    difficulty: "Intermediate",
    estimatedTime: "15 Minutes",
    toolsNeeded: ["Clean 2-Liter Plastic Bottle or Gerry Can", "1 Meter of 5/16\" Fuel Hose", "Flathead Screwdriver"],
    consumables: ["Clean Diesel Fuel", "Zip Ties"],
    overview: "If stranded off-road with a punctured fuel tank, severed chassis fuel line, or failed primer pump head, this emergency field trick allows the 2L-T to drive out under its own power by feeding fuel directly into the injection pump.",
    steps: [
      {
        stepNumber: 1,
        title: "Prepare Clean Fuel Container",
        instruction: "Fill a clean plastic container or Jerry can with fresh diesel. Secure the container safely inside the engine bay (or strapped above the radiator) using zip ties or ratchet straps."
      },
      {
        stepNumber: 2,
        title: "Connect Direct Suction Line to VE Pump Inlet",
        instruction: "Disconnect the rubber hose at the VE injection pump fuel inlet (17mm banjo fitting). Connect a 1-meter length of 5/16\" hose directly from the pump inlet submerged to the bottom of the diesel bottle."
      },
      {
        stepNumber: 3,
        title: "Submerge Return Spill Line into Bottle",
        instruction: "Disconnect the 6mm fuel return hose at the firewall and insert it into the same bottle so excess return fuel circulates back into the container."
      },
      {
        stepNumber: 4,
        title: "Siphon Prime & Crank Engine",
        instruction: "Siphon diesel down the hose until full to prime the pump inlet, slip onto pump fitting, and crank engine. The VE internal vane pump will suck diesel directly from the bottle and run the engine smoothly."
      }
    ]
  }
];
